"""update table bug

Revision ID: b8f16c7789de
Revises: e71d54df9cba
Create Date: 2025-09-24 15:39:16.982656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f16c7789de'
down_revision: Union[str, Sequence[str], None] = 'e71d54df9cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bugs', 'reporter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bugs', 'reporter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
