"""update table task

Revision ID: dc2b414f006f
Revises: 98fc03b7eec7
Create Date: 2025-09-24 12:53:07.270886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2b414f006f'
down_revision: Union[str, Sequence[str], None] = '98fc03b7eec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.String(length=100), nullable=False))
    op.drop_column('tasks', 'Task_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('Task_title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###
